//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoEKZA.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUser { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FIO { get; set; }
        public string Email { get; set; }
        public int IdRole { get; set; }
        public byte[] Photo { get; set; }
        public int IdGender { get; set; }
        public string Phone { get; set; }
        public int IdNapravlenie { get; set; }
        public int IdEvent { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Napravlenie Napravlenie { get; set; }
        public virtual Role Role { get; set; }
    }
}
